services:
  - type: web
    name: universal-docs-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd frontend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11